const KEY="myroutine-fixed-v2";let db=JSON.parse(localStorage.getItem(KEY)||'{"routines":[],"medicines":[],"bp":[],"appointments":[],"water":0,"waterDate":""}');
const $=id=>document.getElementById(id),today=()=>new Date().toISOString().slice(0,10),id=()=>Date.now().toString()+Math.random().toString(16).slice(2);
function save(){localStorage.setItem(KEY,JSON.stringify(db));render()}function toast(x){$("toast").textContent=x;$("toast").classList.add("show");setTimeout(()=>$("toast").classList.remove("show"),1800)}
function resetWater(){if(db.waterDate!==today()){db.water=0;db.waterDate=today();localStorage.setItem(KEY,JSON.stringify(db))}}
function close(){ $("backdrop").classList.remove("show") }
function open(content){$("modal").innerHTML=content;$("backdrop").classList.add("show")}
function form(kind){
let c="";
if(kind==="routine")c=`<h2>New routine</h2><p class=sub>Create a reminder for today.</p><form class=form id=f><div class=field><label>ROUTINE NAME</label><input name=name placeholder="Morning walk" required></div><div class=row><div class=field><label>DATE</label><input name=date type=date value=${today()} required></div><div class=field><label>TIME</label><input name=time type=time required></div></div><button class=primary>Save routine</button></form>`;
if(kind==="medicine")c=`<h2>Medicine reminder</h2><p class=sub>Add medicine to your routine.</p><form class=form id=f><div class=field><label>MEDICINE NAME</label><input name=name placeholder="Medicine name" required></div><div class=row><div class=field><label>DOSE</label><input name=dose placeholder="1 tablet"></div><div class=field><label>TIME</label><input name=time type=time required></div></div><div class=field><label>DATE</label><input name=date type=date value=${today()} required></div><button class=primary>Save medicine</button></form>`;
if(kind==="bp")c=`<h2>Record BP</h2><p class=sub>Save your reading for personal tracking.</p><form class=form id=f><div class=row><div class=field><label>SYS</label><input name=sys type=number required></div><div class=field><label>DIA</label><input name=dia type=number required></div></div><div class=row><div class=field><label>PULSE</label><input name=pulse type=number></div><div class=field><label>TIME</label><input name=time type=time></div></div><div class=field><label>NOTE</label><textarea name=note rows=2></textarea></div><button class=primary>Save BP reading</button></form>`;
if(kind==="appointment")c=`<h2>Appointment</h2><p class=sub>Save an upcoming appointment.</p><form class=form id=f><div class=field><label>TITLE</label><input name=title placeholder="Doctor appointment" required></div><div class=row><div class=field><label>DATE</label><input name=date type=date required></div><div class=field><label>TIME</label><input name=time type=time required></div></div><div class=field><label>LOCATION</label><input name=location placeholder="Optional"></div><button class=primary>Save appointment</button></form>`;
if(kind==="water")c=`<h2>Add water</h2><p class=sub>Today's total: ${db.water} ml</p><div class=choice><button data-water=250>💧 <b>+250 ml</b></button><button data-water=500>💧 <b>+500 ml</b></button><button data-water=750>💧 <b>+750 ml</b></button><button data-water=1000>💧 <b>+1 L</b></button></div>`;
open(c);
const f=$("f");if(f)f.onsubmit=e=>{e.preventDefault();let x=new FormData(f);if(kind==="routine")db.routines.push({id:id(),title:x.get("name"),time:x.get("time"),date:x.get("date"),done:false});if(kind==="medicine")db.medicines.push({id:id(),title:"💊 "+x.get("name"),dose:x.get("dose"),time:x.get("time"),date:x.get("date"),done:false});if(kind==="bp")db.bp.unshift({id:id(),sys:x.get("sys"),dia:x.get("dia"),pulse:x.get("pulse"),time:x.get("time"),date:today(),note:x.get("note")});if(kind==="appointment")db.appointments.push({id:id(),title:x.get("title"),date:x.get("date"),time:x.get("time"),location:x.get("location")});save();close();toast("Saved successfully ✓")};
document.querySelectorAll("[data-water]").forEach(b=>b.onclick=()=>{resetWater();db.water+=Number(b.dataset.water);save();toast("Water added 💧");form("water")});
}
function menu(){open(`<h2>Add something</h2><p class=sub>Choose an option.</p><div class=choice><button data-choice=routine>⏰ <b>Routine</b></button><button data-choice=medicine>💊 <b>Medicine</b></button><button data-choice=bp>🩺 <b>BP</b></button><button data-choice=water>💧 <b>Water</b></button><button data-choice=appointment>📅 <b>Appointment</b></button></div>`);document.querySelectorAll("[data-choice]").forEach(b=>b.onclick=()=>form(b.dataset.choice))}
function render(){resetWater();$("date").textContent=new Date().toLocaleDateString("en-IN",{weekday:"long",day:"numeric",month:"long"});let h=new Date().getHours();$("greeting").textContent=h<12?"Good morning 👋":h<17?"Good afternoon ☀️":"Good evening 🌙";$("medCount").textContent=db.medicines.length;$("bpCount").textContent=db.bp.length;$("waterCount").textContent=db.water;$("apptCount").textContent=db.appointments.length;let t=[...db.routines.filter(x=>x.date===today()),...db.medicines.filter(x=>x.date===today())].sort((a,b)=>(a.time||"").localeCompare(b.time||""));let done=t.filter(x=>x.done).length;let p=t.length?Math.round(done/t.length*100):0;$("percent").textContent=p+"%";$("tasks").innerHTML=t.length?t.map(x=>`<div class="task ${x.done?"done":""}"><button class=check data-id="${x.id}">${x.done?"✓":"○"}</button><div><b>${x.title}</b><small>${x.time||""}${x.dose?" • "+x.dose:""}</small></div></div>`).join(""):`<div class=empty>No routines for today.<br>Tap + Add to create one.</div>`;document.querySelectorAll("[data-id]").forEach(b=>b.onclick=()=>{let x=[...db.routines,...db.medicines].find(x=>x.id===b.dataset.id);if(x){x.done=!x.done;save()}})}
$("close").onclick=close;$("backdrop").onclick=e=>{if(e.target===$("backdrop"))close()};$("add").onclick=menu;$("addRoutine").onclick=()=>form("routine");$("notify").onclick=async()=>{if(!("Notification"in window)){toast("Notifications not supported");return}let p=await Notification.requestPermission();toast(p==="granted"?"Notifications enabled 🔔":"Permission not granted")};$("settings").onclick=()=>open(`<h2>Settings</h2><p class=sub>Your data is stored on this device in this version.</p><button class=secondary id=export>Export backup</button><br><br><button class=secondary id=clear>Clear all data</button>`);document.addEventListener("click",e=>{let b=e.target.closest("[data-action]");if(b)form(b.dataset.action);let ex=e.target.closest("#export");if(ex){let a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(db,null,2)],{type:"application/json"}));a.download="myroutine-backup.json";a.click();toast("Backup exported")}let cl=e.target.closest("#clear");if(cl&&confirm("Delete all MyRoutine data?")){localStorage.removeItem(KEY);location.reload()}});render();